spring:
  application:
    name: mcp-server-demo
#  main:
#    web-application-type: none
#    banner-mode: off
  ai:
    mcp:
      server:
        name: mcp-server
        version: 1.0.0
        enabled: true
        stdio: false
        resource-change-notification: true
        tool-change-notification: true
        prompt-change-notification: true
        sse-endpoint: /api/v1/sse
        sse-message-endpoint: /api/v1/mcp
        type: sync
        capabilities:
          tool: true
          resource: true
          prompt: true
          completion: true

logging:
  level:
    io.modelcontextprotocol: TRACE
    org.springframework.ai.mcp: TRACE